version: 2
jobs:
  build:
    working_directory: ~/9anime-Companion
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Update NPM
          command: npm install -g npm@latest
      # Download and cache dependencies
      - restore_cache:
          keys:
          - 1.0.0-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - 1.0.0-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: 1.0.0-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint typescript
          command: npm run linter
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build wee!
          command: npm run build
      - store_artifacts:
          path: /dist/9anime_Companion-chrome-1.0.0.zip
          destination: 9anime_Companion-chrome-1.0.0.zip
